version: "3"
services:
  client:
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "10000:10000"
    volumes:
      - "/app/node_modules"
      - "./:/app"